cli options parser added, project creation logic changed

diff --git a/activate_external_repos b/activate_external_repos
--- a/activate_external_repos
+++ b/activate_external_repos
@@ -1,47 +1,102 @@
-#!/bin/bash -x
-INDEX_URL=$1
-PROJECT=$2
-REPO_NAME=$3
-PACKAGE_TYPE="RPM"
-ARCH="x86_64"
-if [[ -z "$INDEX_URL" || -z "$PROJECT" || -z "$REPO_NAME" ]]; then
-	echo -e "Invalid usage\nUsage: $(basename $0) <repo_index(primary.xml.gz or Packages.bz2)_url> <target_project_name> <repo_name> [<package_type>=RPM] [<arch>=x86_64]\nFor RPM repos specify repository baseurl, for DEB repos - exact link to Packages.bz2 file\n"
+#!/bin/bash
+while getopts ":u:p:t:n:a:d:c:hA:" FLAG; do
+	case $FLAG in
+		u)
+			REPO_URL=$OPTARG
+			;;
+		t)
+			REPO_TYPE=$OPTARG
+			;;
+		p)
+			PROJECT=$OPTARG
+			;;
+		a)
+			ARCH=$OPTARG
+			;;
+		n)
+			REPO_NAME=$OPTARG
+			;;
+		d)
+			UBUNTU_DISTRO=$OPTARG
+			;;
+		c)
+			UBUNTU_REPO_COMPONENT=$OPTARG
+			;;
+		A)
+			OBS_SERV_URL=$OPTARG
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG. Use -h for help" >&2
+			exit 1
+			;;
+		:)
+			echo "Option -$OPTARG requires an argument." >&2
+			exit 1
+			;;
+		h)
+			echo -e "Usage: $(basename $0) [-A <obs_url>] -u <source_repo_url> -p <obs_project> -n <repository_name> [-t <repo_type>=RPM] [-a <arch>=x86_64] \
+[-d <ubuntu_distro>=precise] [-c <ubuntu_repo_component>=main]\n\n \
+-u <source_repo_url> 		- URL of repository project connected to. Needed for downloading repo index files.\n \
+-p <obs_project>     		- name of OBS project for linking (activating).\n \
+-n <repository_name> 		- desired name of OBS project's repository.\n \
+[-A <obs_url>]			- target OBS server API URL. Default value: OBS_DEST env variable.\n \
+[-t <repo_type>]     		- deb or rpm repository. Default value: RPM.\n \
+[-a <arch>]          		- repository architecture. Default value: x86_64.\n \
+[-d <ubuntu_distro>=precise]	- UBUNTU ONLY: Ubuntu distribution (code name). Default value: precise.\n \
+[-c <ubuntu_repo_component>=main]-UBUNTU ONLY: Ubuntu repo component, e.g. main, universe, multiverse etc. Default value: main."
+				
+			exit
+			;;
+	esac
+done
+shift $((OPTIND-1))
+
+if [[ -z "$REPO_URL" || -z "$PROJECT" || -z "$REPO_NAME" ]]; then
+	echo "Invalid usage. <repo_url>, <obs-project> and <repository_name> arguments are mandatory. Use -h fo help."
 	exit 1
 fi
-if [[ -n "$4" ]]; then	
-	PACKAGE_TYPE=$4
-fi
-case "$PACKAGE_TYPE" in
+[[ -z "$OBS_SERV_URL" ]] && OBS_SERV_URL=$OBS_DEST
+[[ -z "$REPO_TYPE" ]] && REPO_TYPE="RPM"
+[[ -z "$ARCH" ]] && ARCH="x86_64"
+[[ -z "$UBUNTU_DISTRO" ]] && UBUNTU_DISTRO="precise"
+[[ -z "$UBUNTU_REPO_COMPONENT" ]] && UBUNTU_REPO_COMPONENT="main"
+case "$REPO_TYPE" in
 	"RPM"|"rpm")
 		INDEX_TYPE="primary.xml.gz"
 		# determine exact path to primary.xml.gz file in repodata
-		INDEX_URL="${INDEX_URL%/}/repodata/$(curl ${INDEX_URL%/}/repodata/ | grep -o '[0-9a-hA-H-]*primary\.xml\.gz' | uniq)"
+		INDEX_URL="${REPO_URL%/}/repodata/$(curl ${INDEX_URL%/}/repodata/ | grep -o '[0-9a-hA-H-]*primary\.xml\.gz' | uniq)"
 		UNZIPPER="gunzip"
 		;;
 	"DEB"|"deb")
-		INDEX_TYPE="Packages.bz2"
-		UNZIPPER="bunzip2"
+		INDEX_TYPE="Packages.gz"
+		DIST="precise"
+
+		INDEX_URL="${REPO_URL%/}/dist/$UBUNTU_DISTRO/$UBUNTU_REPO_COMPONENT/binary-$(echo $ARCH | sed 's|^x86_64$|amd64|;s|^x86$|i386|')/$INDEX_TYPE"
+		UNZIPPER="gunzip"
 		;;
 	*)
 		echo "Invalid package_type. Should be either RPM or DEB"
 		exit 1
 		;;
 esac
-if [[ -n "$5" ]]; then
-	ARCH=$5
-fi
-# copy prj and prjconf of target/external project
-osc -A $OBS_SOURCE meta prj $PROJECT > $PROJECT.prj
-osc -A $OBS_SOURCE meta prjconf $PROJECT > $PROJECT.prjconf
 # create target/external project on destination OBS
-if ! osc -A $OBS_DEST meta prj -F $PROJECT.prj $PROJECT; then 
+if ! osc -A $OBS_DEST meta prj -F - $PROJECT <<EOF
+<project name="internal:ubuntu-osci-builddeps-5.1">
+  <title/>
+  <description/>
+  <person userid="Admin" role="bugowner"/>
+  <person userid="Admin" role="maintainer"/>
+  <download baseurl="$INDEX_URL" metafile="${INDEX_TYPE%.*}" mtype="$(echo $REPO_TYPE | tr '[:upper:]' '[:lower:]')md" arch="$ARCH"/>
+  <repository name="$UBUNTU_DISTRO-$UBUNTU_REPO_COMPONENT">
+    <arch>$ARCH</arch>
+  </repository>
+</project>
+EOF
+then
+
 	echo "Project wasn't created. Exitting..."
-	rm -f $PROJECT.{prj,prjconf}
 	exit 1
 fi
-osc -A $OBS_DEST meta prjconf -F $PROJECT.prjconf $PROJECT
-# remove temporary files with project configs
-rm -f $PROJECT.{prj,prjconf}
 if [[ ! -d /srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full ]]; then
 	if ! mkdir -p /srv/obs/build/$PROJECT/$REPO_NAME/$ARCH/:full; then echo ":full directory for project $PROJECT wasn't created. Exitting..."; exit 2; fi
 else
